[package]
name = "proxy-provider"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
fiberplane-provider-bindings = { workspace = true }
rmp-serde = "1.0.0"
urlencoding = "2"
