[package]
name = "fp-provider-protocol"
version = "2.0.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[dependencies]
bytes = "1"
fiberplane = { path = "../fiberplane" }
fp-bindgen = { version = "2", features = ["bytes-compat", "generators"] }
serde_json = "1"
