[workspace]
members = [
    "base64uuid",
    "fiberplane",
    "fp-api-client",
    "fp-markdown",
    "fp-provider-protocol",
    "fp-provider-protocol/fp-provider-bindings",
    "fp-provider-protocol/fp-provider-runtime",
    "fp-templates",
    "providers/*",
    "time_util",
]

[patch.crates-io]
# fp-bindgen = { path = "../fp-bindgen/fp-bindgen"}
# fp-bindgen-macros = { path = "../fp-bindgen/macros"}
# fp-bindgen-support = { path = "../fp-bindgen/fp-bindgen-support"}
fp-bindgen = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main" }
fp-bindgen-macros = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main" }
fp-bindgen-support = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main" }
