[workspace]
members = [
    "api_client",
    "base64uuid",
    "fiberplane",
    "markdown",
    "provider-protocol",
    "provider-protocol/fp-provider-bindings",
    "provider-protocol/fp-provider-runtime",
    "providers/*",
    "templates",
    "time_util",
]
