[workspace]
members = [
    "base64uuid",
    "fiberplane",
    "fp-api-client",
    "fp-markdown",
    "fp-provider-protocol",
    "fp-provider-protocol/fp-provider-bindings",
    "fp-provider-protocol/fp-provider-runtime",
    "fp-templates",
    "providers/*",
    "time_util",
]

[patch.crates-io]
#fp-bindgen = { path = "../fp-bindgen/fp-bindgen" }
