[package]
name = "fiberplane"
version = "0.1.0"
authors = ["Benno van den Berg <benno@fiberplane.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
fp-bindgen = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main", features = [
    "chrono-compat",
] }
#fp-bindgen = { path = "../fp-bindgen/fp-bindgen", features = ["chrono-compat"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
once_cell = "1.8"
pretty_assertions = "0.7"
