[package]
name = "fiberplane"
version = "0.1.0"
authors = ["Benno van den Berg <benno@fiberplane.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
