[package]
name = "fiberplane"
version = "0.1.0"
authors = ["Benno van den Berg <benno@fiberplane.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
fp-bindgen = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main", features = [
    "time-compat",
] }
# fp-bindgen = { path = "../fp-bindgen/fp-bindgen", features = ["time-compat"] }
once_cell = "1.8"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
time = { version = "0.3", features = ["serde-human-readable"] }
time_util = { path = "../time_util" }

[dev-dependencies]
pretty_assertions = "0.7"
serde_json = "1.0"
