[package]
name = "base64uuid"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
serde = { version = "1.0.133", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
thiserror = "1.0.30"

[dev-dependencies]
serde_json = "1.0.74"
