/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CellReplaceText {
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "newText")]
    pub new_text: String,
    #[serde(rename = "newFormatting", skip_serializing_if = "Option::is_none")]
    pub new_formatting: Option<Vec<crate::models::Annotation>>,
    #[serde(rename = "oldText")]
    pub old_text: String,
    #[serde(rename = "oldFormatting", skip_serializing_if = "Option::is_none")]
    pub old_formatting: Option<Vec<crate::models::Annotation>>,
}

impl CellReplaceText {
    pub fn new(offset: i32, new_text: String, old_text: String) -> CellReplaceText {
        CellReplaceText {
            offset,
            new_text,
            new_formatting: None,
            old_text,
            old_formatting: None,
        }
    }
}
