/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataSourceAndProxySummary {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub _type: crate::models::DataSourceType,
    #[serde(rename = "proxy")]
    pub proxy: Box<crate::models::ProxySummary>,
}

impl DataSourceAndProxySummary {
    pub fn new(name: String, _type: crate::models::DataSourceType, proxy: crate::models::ProxySummary) -> DataSourceAndProxySummary {
        DataSourceAndProxySummary {
            name,
            _type,
            proxy: Box::new(proxy),
        }
    }
}


