/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataSourceConnectionStatus {
    #[serde(rename = "connected")]
    Connected,
    #[serde(rename = "error")]
    Error,
}

impl ToString for DataSourceConnectionStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Connected => String::from("connected"),
            Self::Error => String::from("error"),
        }
    }
}
