/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElasticsearchDataSource {
    #[serde(rename = "type")]
    pub _type: crate::models::DataSourceType,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "timestampFieldNames")]
    pub timestamp_field_names: Vec<String>,
    #[serde(rename = "bodyFieldNames")]
    pub body_field_names: Vec<String>,
}

impl ElasticsearchDataSource {
    pub fn new(_type: crate::models::DataSourceType, url: String, timestamp_field_names: Vec<String>, body_field_names: Vec<String>) -> ElasticsearchDataSource {
        ElasticsearchDataSource {
            _type,
            url,
            timestamp_field_names,
            body_field_names,
        }
    }
}


