/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElasticsearchFieldMappings {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<crate::models::Array>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<crate::models::Array>,
}

impl ElasticsearchFieldMappings {
    pub fn new() -> ElasticsearchFieldMappings {
        ElasticsearchFieldMappings {
            timestamp: None,
            body: None,
        }
    }
}


