/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElasticsearchDataSource {
    #[serde(rename = "type")]
    pub _type: crate::models::DataSourceType,
    #[serde(rename = "url")]
    pub url: String,
}

impl ElasticsearchDataSource {
    pub fn new(_type: crate::models::DataSourceType, url: String) -> ElasticsearchDataSource {
        ElasticsearchDataSource {
            _type,
            url,
        }
    }
}


