/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "labels")]
    pub labels: ::std::collections::HashMap<String, String>,
    #[serde(rename = "occurrenceTime")]
    pub occurrence_time: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Event {
    pub fn new(id: String, title: String, labels: ::std::collections::HashMap<String, String>, occurrence_time: String, created_at: String, updated_at: String) -> Event {
        Event {
            id,
            title,
            labels,
            occurrence_time,
            created_at,
            updated_at,
        }
    }
}


