/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantQuery {
    #[serde(rename = "type")]
    pub _type: String,
    #[serde(rename = "time")]
    pub time: f64,
}

impl InstantQuery {
    pub fn new(_type: String, time: f64) -> InstantQuery {
        InstantQuery {
            _type,
            time,
        }
    }
}


