/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MentionAnnotation {
    #[serde(rename = "type")]
    pub _type: crate::models::AnnotationType,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl MentionAnnotation {
    pub fn new(_type: crate::models::AnnotationType, offset: i32, name: String, user_id: String) -> MentionAnnotation {
        MentionAnnotation {
            _type,
            offset,
            name,
            user_id,
        }
    }
}


