/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotebookSearch {
    /// Search notebooks based on labels. You can search for an exact label match by supplying both an key and a value. You can also search for all labels that have a specific key by passing passing a key with a null value or a empty string value. The notebook's labels needs to match _every_ label search that is provided.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
}

impl NotebookSearch {
    pub fn new() -> NotebookSearch {
        NotebookSearch { labels: None }
    }
}
