/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProxyDataSource {
    #[serde(rename = "type")]
    pub _type: crate::models::DataSourceType,
    #[serde(rename = "proxyId")]
    pub proxy_id: String,
    #[serde(rename = "dataSourceName")]
    pub data_source_name: String,
    #[serde(rename = "dataSourceType")]
    pub data_source_type: crate::models::DataSourceType,
}

impl ProxyDataSource {
    pub fn new(
        _type: crate::models::DataSourceType,
        proxy_id: String,
        data_source_name: String,
        data_source_type: crate::models::DataSourceType,
    ) -> ProxyDataSource {
        ProxyDataSource {
            _type,
            proxy_id,
            data_source_name,
            data_source_type,
        }
    }
}
