/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SentryDataSource {
    #[serde(rename = "organizationSlug")]
    pub organization_slug: String,
    #[serde(rename = "projectSlug")]
    pub project_slug: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "type")]
    pub _type: crate::models::DataSourceType,
}

impl SentryDataSource {
    pub fn new(
        organization_slug: String,
        project_slug: String,
        token: String,
        _type: crate::models::DataSourceType,
    ) -> SentryDataSource {
        SentryDataSource {
            organization_slug,
            project_slug,
            token,
            _type,
        }
    }
}
