/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TemplateParameter {
    #[serde(rename="array")]
    ArrayTemplateParameter {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
        default_value: Option<Vec<serde_json::Value>>,
    },
    #[serde(rename="boolean")]
    BooleanTemplateParameter {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
        default_value: Option<bool>,
    },
    #[serde(rename="number")]
    NumberTemplateParameter {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
        default_value: Option<f32>,
    },
    #[serde(rename="object")]
    ObjectTemplateParameter {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
        default_value: Option<serde_json::Value>,
    },
    #[serde(rename="string")]
    StringTemplateParameter {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
        default_value: Option<String>,
    },
    #[serde(rename="unknown")]
    UnknownTemplateParameter {
        #[serde(rename = "name")]
        name: String,
    },
}




