/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "firstItem")]
    pub first_item: Box<crate::models::ThreadItem>,
    /// Most recent thread items, sorted in chronological order
    #[serde(rename = "recentItems")]
    pub recent_items: Vec<crate::models::ThreadItem>,
    #[serde(rename = "status")]
    pub status: crate::models::ThreadStatus,
    #[serde(rename = "createdBy")]
    pub created_by: Box<crate::models::UserSummary>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ThreadSummary {
    pub fn new(
        id: String,
        first_item: crate::models::ThreadItem,
        recent_items: Vec<crate::models::ThreadItem>,
        status: crate::models::ThreadStatus,
        created_by: crate::models::UserSummary,
        created_at: String,
        updated_at: String,
    ) -> ThreadSummary {
        ThreadSummary {
            id,
            first_item: Box::new(first_item),
            recent_items,
            status,
            created_by: Box::new(created_by),
            created_at,
            updated_at,
        }
    }
}
