/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggerInvokeResponse {
    #[serde(rename = "notebookTitle")]
    pub notebook_title: String,
    #[serde(rename = "notebookId")]
    pub notebook_id: String,
    #[serde(rename = "notebookUrl")]
    pub notebook_url: String,
}

impl TriggerInvokeResponse {
    pub fn new(
        notebook_title: String,
        notebook_id: String,
        notebook_url: String,
    ) -> TriggerInvokeResponse {
        TriggerInvokeResponse {
            notebook_title,
            notebook_id,
            notebook_url,
        }
    }
}
