/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Trigger {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "templateId")]
    pub template_id: String,
    /// This key must be passed in the URL to invoke the trigger
    #[serde(rename = "secretKey", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    #[serde(rename = "defaultArguments", skip_serializing_if = "Option::is_none")]
    pub default_arguments: Option<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Trigger {
    pub fn new(id: String, title: String, template_id: String, created_at: String, updated_at: String) -> Trigger {
        Trigger {
            id,
            title,
            template_id,
            secret_key: None,
            default_arguments: None,
            created_at,
            updated_at,
        }
    }
}


