/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentDeleteThreadItem {
    #[serde(rename = "type")]
    pub _type: crate::models::ThreadItemType,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdBy")]
    pub created_by: Box<crate::models::UserSummary>,
    /// Timestamp when the original comment was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "deletedAt")]
    pub deleted_at: String,
}

impl CommentDeleteThreadItem {
    pub fn new(
        _type: crate::models::ThreadItemType,
        id: String,
        created_by: crate::models::UserSummary,
        created_at: String,
        deleted_at: String,
    ) -> CommentDeleteThreadItem {
        CommentDeleteThreadItem {
            _type,
            id,
            created_by: Box::new(created_by),
            created_at,
            deleted_at,
        }
    }
}
