/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentThreadItemAllOf {
    #[serde(rename = "type")]
    pub _type: crate::models::ThreadItemType,
}

impl CommentThreadItemAllOf {
    pub fn new(_type: crate::models::ThreadItemType) -> CommentThreadItemAllOf {
        CommentThreadItemAllOf { _type }
    }
}
