/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CreatedBy {
    #[serde(rename = "trigger")]
    CreatedByTrigger {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "title")]
        title: String,
        #[serde(rename = "templateId")]
        template_id: String,
        #[serde(rename = "createdAt")]
        created_at: String,
        #[serde(rename = "updatedAt")]
        updated_at: String,
    },
    #[serde(rename = "unknown")]
    CreatedByUnknown {},
    #[serde(rename = "user")]
    CreatedByUser {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
    },
}
