/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteEvent {
    #[serde(rename = "id")]
    pub id: String,
}

impl DeleteEvent {
    pub fn new(id: String) -> DeleteEvent {
        DeleteEvent {
            id,
        }
    }
}


