/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogCellVisibility {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "selected")]
    Selected,
    #[serde(rename = "highlighted")]
    Highlighted,
}

impl ToString for LogCellVisibility {
    fn to_string(&self) -> String {
        match self {
            Self::All => String::from("all"),
            Self::Selected => String::from("selected"),
            Self::Highlighted => String::from("highlighted"),
        }
    }
}
