/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWorkspaceInvite {
    #[serde(rename = "email")]
    pub email: String,
}

impl NewWorkspaceInvite {
    pub fn new(email: String) -> NewWorkspaceInvite {
        NewWorkspaceInvite { email }
    }
}
