/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWorkspaceInvite {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "role")]
    pub role: Role,
}

impl NewWorkspaceInvite {
    pub fn new(email: String, role: Role) -> NewWorkspaceInvite {
        NewWorkspaceInvite { email, role }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "admin")]
    Admin,
}
