/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelativeTimeRange {
    #[serde(rename = "relative")]
    pub relative: i32,
}

impl RelativeTimeRange {
    pub fn new(relative: i32) -> RelativeTimeRange {
        RelativeTimeRange { relative }
    }
}
