/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectedDataSource {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "proxyName", skip_serializing_if = "Option::is_none")]
    pub proxy_name: Option<String>,
}

impl SelectedDataSource {
    pub fn new(name: String) -> SelectedDataSource {
        SelectedDataSource {
            name,
            proxy_name: None,
        }
    }
}
