/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableRow {
    #[serde(rename = "cols")]
    pub cols: Vec<crate::models::TableColumn>,
}

impl TableRow {
    pub fn new(cols: Vec<crate::models::TableColumn>) -> TableRow {
        TableRow { cols }
    }
}
