/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeRange {
    #[serde(rename = "from")]
    pub from: f64,
    #[serde(rename = "to")]
    pub to: f64,
}

impl TimeRange {
    pub fn new(from: f64, to: f64) -> TimeRange {
        TimeRange { from, to }
    }
}
