/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggerSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "templateId")]
    pub template_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl TriggerSummary {
    pub fn new(
        id: String,
        title: String,
        template_id: String,
        created_at: String,
        updated_at: String,
    ) -> TriggerSummary {
        TriggerSummary {
            id,
            title,
            template_id,
            created_at,
            updated_at,
        }
    }
}
