/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceInviteResponse {
    #[serde(rename = "url")]
    pub url: String,
}

impl WorkspaceInviteResponse {
    pub fn new(url: String) -> WorkspaceInviteResponse {
        WorkspaceInviteResponse { url }
    }
}
