[package]
name = "fiberplane-string-utils"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ["lib"]

[dependencies]
