/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogCell {
    #[serde(rename = "type")]
    pub _type: crate::models::CellType,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "dataLinks")]
    pub data_links: Vec<String>,
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "hideSimilarValues", skip_serializing_if = "Option::is_none")]
    pub hide_similar_values: Option<bool>,
    #[serde(rename = "displayFields", skip_serializing_if = "Option::is_none")]
    pub display_fields: Option<Vec<String>>,
    #[serde(rename = "expandedIndices", skip_serializing_if = "Option::is_none")]
    pub expanded_indices: Option<Vec<crate::models::LogRecordIndex>>,
    #[serde(rename = "visibilityFilter", skip_serializing_if = "Option::is_none")]
    pub visibility_filter: Option<crate::models::LogCellVisibility>,
    #[serde(rename = "selectedIndices", skip_serializing_if = "Option::is_none")]
    pub selected_indices: Option<Vec<crate::models::LogRecordIndex>>,
    #[serde(rename = "highlightedIndices", skip_serializing_if = "Option::is_none")]
    pub highlighted_indices: Option<Vec<crate::models::LogRecordIndex>>,
}

impl LogCell {
    pub fn new(_type: crate::models::CellType, id: String, data_links: Vec<String>) -> LogCell {
        LogCell {
            _type,
            id,
            data_links,
            read_only: None,
            hide_similar_values: None,
            display_fields: None,
            expanded_indices: None,
            visibility_filter: None,
            selected_indices: None,
            highlighted_indices: None,
        }
    }
}
