/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWorkspace {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// This is a mapping from the provider type to the data source selected for that type
    #[serde(rename = "defaultDataSources", skip_serializing_if = "Option::is_none")]
    pub default_data_sources:
        Option<::std::collections::HashMap<String, crate::models::SelectedDataSource>>,
}

impl NewWorkspace {
    pub fn new(name: String) -> NewWorkspace {
        NewWorkspace {
            name,
            display_name: None,
            default_data_sources: None,
        }
    }
}
