/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NewTimeRange {
    Absolute(crate::models::TimeRange),
    Relative(RelativeTimeRange),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelativeTimeRange {
    pub minutes: i32,
}
