/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewComment {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "formatting", skip_serializing_if = "Option::is_none")]
    pub formatting: Option<Vec<crate::models::Annotation>>,
}

impl NewComment {
    pub fn new(content: String) -> NewComment {
        NewComment {
            id: None,
            content,
            formatting: None,
        }
    }
}
