/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewDataSource {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
    #[serde(rename = "providerType")]
    pub provider_type: String,
    #[serde(rename = "config")]
    pub config: serde_json::Value,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl NewDataSource {
    pub fn new(
        name: String,
        protocol_version: i32,
        provider_type: String,
        config: serde_json::Value,
    ) -> NewDataSource {
        NewDataSource {
            name,
            protocol_version,
            provider_type,
            config,
            description: None,
        }
    }
}
