/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewNotebook {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "timeRange")]
    pub time_range: Box<crate::models::NewTimeRange>,
    #[serde(rename = "cells")]
    pub cells: Vec<crate::models::Cell>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<crate::models::Label>>,
    /// This is a mapping from the provider type to the data source selected for that type
    #[serde(
        rename = "selectedDataSources",
        skip_serializing_if = "Option::is_none"
    )]
    pub selected_data_sources:
        Option<::std::collections::HashMap<String, crate::models::SelectedDataSource>>,
}

impl NewNotebook {
    pub fn new(
        title: String,
        time_range: crate::models::NewTimeRange,
        cells: Vec<crate::models::Cell>,
    ) -> NewNotebook {
        NewNotebook {
            title,
            time_range: Box::new(time_range),
            cells,
            labels: None,
            selected_data_sources: None,
        }
    }
}
