/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Profile {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "defaultWorkspaceId")]
    pub default_workspace_id: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// This contains a mapping of the workspace ID and the role that the user has in the workspace
    #[serde(rename = "roles")]
    pub roles: ::std::collections::HashMap<String, crate::models::AuthRole>,
}

impl Profile {
    pub fn new(
        id: String,
        name: String,
        default_workspace_id: String,
        roles: ::std::collections::HashMap<String, crate::models::AuthRole>,
    ) -> Profile {
        Profile {
            id,
            name,
            default_workspace_id,
            email: None,
            roles,
        }
    }
}
