/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusChangeThreadItem {
    #[serde(rename = "type")]
    pub _type: crate::models::ThreadItemType,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: crate::models::ThreadStatus,
    #[serde(rename = "createdBy")]
    pub created_by: Box<crate::models::UserSummary>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl StatusChangeThreadItem {
    pub fn new(
        _type: crate::models::ThreadItemType,
        id: String,
        status: crate::models::ThreadStatus,
        created_by: crate::models::UserSummary,
        created_at: String,
    ) -> StatusChangeThreadItem {
        StatusChangeThreadItem {
            _type,
            id,
            status,
            created_by: Box::new(created_by),
            created_at,
        }
    }
}
