/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Thread {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ThreadItem>,
    #[serde(rename = "status")]
    pub status: crate::models::ThreadStatus,
    #[serde(rename = "createdBy")]
    pub created_by: Box<crate::models::UserSummary>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Thread {
    pub fn new(
        id: String,
        items: Vec<crate::models::ThreadItem>,
        status: crate::models::ThreadStatus,
        created_by: crate::models::UserSummary,
        created_at: String,
        updated_at: String,
    ) -> Thread {
        Thread {
            id,
            items,
            status,
            created_by: Box::new(created_by),
            created_at,
            updated_at,
        }
    }
}
