/*
 * Fiberplane API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceUserUpdate {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<crate::models::AuthRole>,
}

impl WorkspaceUserUpdate {
    pub fn new() -> WorkspaceUserUpdate {
        WorkspaceUserUpdate { role: None }
    }
}
