name: TypeScript package audit

on:
  push:
    paths:
      - "**/package.json"
      - "**/yarn.lock"
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit_ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn --immutable

      - name: Run security audit
        run: yarn workspaces foreach npm audit
