name: Build

on:
  push:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup-git-credentials
      uses: fusion-engineering/setup-git-credentials@v2.0.6
      with:
        credentials: "https://fiberplanebot:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/"

    - id: branch
      name: Export branch
      run: echo "::set-output name=branch::${GITHUB_HEAD_REF:-${GITHUB_REF##refs/heads/}}"

    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
      
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt

    - name: add rust components
      run: rustup component add clippy

    - name: Check format
      # Run on nightly so we can use the unstable ignore feature
      # and ignore the generated API client
      run: cargo +nightly fmt -- --check

    - name: Lint code
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: >
          --all-features 
          -p fiberplane 
          -p time_util
          -p base64uuid

    - name: Run tests
      run: cargo test --verbose
