name: Build Fiberplane
on:
  push:
    branches: ["main"]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          repository: fiberplane/fake-monorepo
          event-type: build
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
