name: Build and publish docs website

on:
  workflow_call:
    secrets:
      AWS_ROLE_GITHUB_ACTIONS:
        required: true
    inputs:
      docs_bucket_id:
        description: The S3 bucket id where the built docs should be placed
        type: string
        required: true
      docs_cloudfront_id:
        description: The CloudFront instance that should be invalidated
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_GITHUB_ACTIONS }}
          aws-region: eu-central-1

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Build site
        run: yarn build

      - name: Sync to S3 bucket
        run: |
          aws s3 sync --delete ./dist/ s3://${{ inputs.docs_bucket_id }}

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ inputs.docs_cloudfront_id }} \
            --paths '/*'

