---
name: Generate and sync Templates reference to ReadMe

on:
  workflow_dispatch:

env:
  API_DEFINITION_ID: 63d93703167244000ce4542c

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare documentation
        run: cat fiberplane-templates/docs/front-matter.txt fiberplane-templates/docs/template_api.md  > templates_reference.md


      - name: Dry run sync to ReadMe
        uses: readmeio/rdme@v8
        env:
          RDME_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs templates_reference.md --dryRun

      - name: Sync openapi reference to ReadMe
        uses: readmeio/rdme@v8
        env:
          RDME_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs templates_reference.md
